# Generated by Django 3.2 on 2022-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='fecha_entrega',
            field=models.DateTimeField(),
        ),
    ]
