# Generated by Django 3.2 on 2022-03-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ietimoodle', '0002_alter_entrega_fecha_entrega'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ietimoodle.curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ietimoodle.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UsersCurso',
        ),
    ]
